fix: OSError read should return bytes
xbrianh/gs-chunked-io pull request #21
Opened 2020-03-14 01:48 UTC by justindujardin

Thanks for the helpful library. I tried it out and got an `OSError` about `read` needing to return `bytes` instead of `bytesarray`. It looks like this is because the `pathlib.Path` asserts on the return type from read internally. Besides fixing the error, this is more consistent with your type annotations.

2020-03-15 20:14 UTC, xbrianh requested changes
Thank you very much for for taking an interest in my humble library :)

Hopefully we can make it work for your use case. The solution you propose will negatively impact performance since it involves an additional buffer copy for every call to read.  However, I think there's a way to maintain or enhance current performance while returning bytes objects.

If you would like to make the change referenced in my review comments, I will merge in your  PR. Otherwise I will include it in forthcoming read optimizations I have planned.

Thank again for catching my bug!

2020-03-15 20:14 UTC, xbrianh commented on gs_chunked_io/reader.py
> +        return bytes(ret_data)
Casting to bytes unfortunately involves a copy of the underlying buffer, negatively affecting performance. See, [this Stack Overflow post for discussion](https://stackoverflow.com/questions/35880065/does-converting-from-bytearray-to-bytes-incur-a-copy).

However, we can still cast to bytes without increasing the number of buffer copies by taking a slice of a memoryview on line 45:
```
ret_data = bytes(memoryview(self._buffer)[:size])
```

2020-03-16 22:19 UTC, justindujardin commented on gs_chunked_io/reader.py
> +        return bytes(ret_data)
Sure, done!

2020-03-17 04:44 UTC, xbrianh approved these changes

2020-03-17 04:44 UTC, merged

2020-03-17 04:57 UTC, xbrianh commented
This is included in release 0.2.9